### PR TITLE
Instagram_video_downloader

### PR DESCRIPTION
**Pull request by Abubakrce19**
Closes issue 
#18 (instagram video downloader : intermediate)
This is a draft pr, as requested by @sonnynomnom .

- [ ] My project tutorial topic has already been aproved by the Codédex team
- [ ] My project tutorial file renders properly in `mdx`
- [ ] The content written is my own, and not plagiarized from other sources
- [ ] All code written is commented or documented thoroughly
- [ ] I have already completed a self-review of the project tutorial 
- [ ] I will comply with changes from the Codédex team about my project tutorial

### CODE REVIEW

**Comment by Abubakrce19** [comment]
@sonnynomnom please have a look.

**Review by Bobliuuu — CHANGES_REQUESTED** [review]
Hi @Abubakrce19, great work! Just a few changes: 
- Please follow the [formatting guidelines](https://github.com/codedex-io/projects/blob/main/.github/CONTRIBUTING.md).
- Make sure strings are single quotes
- Python indentation is two spaces
- 'Please enter the video ID!'
- You only need one line between the parts of the code
- Just `return` instead of `sys.exit()`

**Comment by Abubakrce19** [comment]
@Bobliuuu 
Changes are done.
But I just used another approach to do this task, this is one is faster and efficient should update the file with new code?

**Review by Bobliuuu — CHANGES_REQUESTED** [review]
LGTM, thanks for making the changes!

**Review by Bobliuuu — APPROVED** [review]

**Comment by Bobliuuu** [comment]
@Abubakrce19 You can start on the project tutorial now! 
If you want to use a different code for your tutorial, please change the code on your branch so we can review it!

**Comment by Bobliuuu** [comment]
Hi @Abubakrce19, that project template is just a template for you to create your project tutorial! 
You need to edit it to write your tutorial, and explain your code using the template provided. 
Let me know if you have more questions 🚀

**Comment by Abubakrce19** [comment]
@Bobliuuu 
Thank you for responding on the week days❤️ too.
I am currently working on this project advancement by creating a gui for this.
And adding more options like downloading profile picture of any account.
I will probably create a new pr for this and close this one.
In the new code I am explaining in detail by comments.
Also the project tutorial will e ready soon.

How can i get the header image template which every project tutorial had?
I am always open for your valuable suggestions.

**Comment by Bobliuuu** [comment]
Hi @Abubakrce19, 

Sounds good! We will create the header image template for you, so don't worry about that!

**Pull request closed without merging**
